# Generated by Django 4.2.5 on 2023-09-30 18:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedTime',
            fields=[
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('project', models.CharField(blank=True, max_length=64, null=True)),
                ('time', models.IntegerField()),
                ('billable', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
